env:
  browser: true
  es2021: true
  node: true
extends:
- standard-with-typescript
- plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
- react
settings:
  react:
    version: "18.0"
rules: {}
