version: "3.8"
services:
  frontend: # React.js frontend
    build:
      context: .
      dockerfile: ./Docker/frontend/Dockerfile
    tty: true
    volumes:
    - ./frontend:/app
    - "/app/node_modules" # 匿名ボリューム
    ports:
    - 3000:3000
    # stdin_open: true
