version: "3.8"
services:
  frontend: # React.js frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    tty: true
    volumes:
    - ./frontend:/app
    - "/app/node_modules"
    ports:
    - 3000:3000
    stdin_open: true
